from pathlib import Path

repls = {
    "Link Copied!": "Ссылка скопирована!",
    "Link copied!": "Ссылка скопирована!",
    "Link copied": "Ссылка скопирована",
    "Invalid Email ID": "Некорректный email",
    "Invitations sent successfully.": "Приглашения успешно отправлены.",
    "Failed": "Ошибка",
    "Oops!": "Упс!",
    "Please select a member": "Выберите участника",
    "Select Role": "Выберите роль",
    "Project added to favorites.": "Проект добавлен в избранное.",
    "Couldn't add the project to favorites. Please try again.": "Не удалось добавить проект в избранное. Попробуйте снова.",
    "Settings": "Настройки",
    "Join": "Присоединиться",
    "Open in new tab": "Открыть в новой вкладке",
    "Copy link": "Копировать ссылку",
    "Restore": "Восстановить",
    "Delete": "Удалить",
    "Search for shortcuts": "Поиск быстрых команд",
    "Search": "Поиск",
    "Cycle created successfully.": "Цикл успешно создан.",
    "Cycle updated successfully.": "Цикл успешно обновлен.",
    "Cycle deleted successfully.": "Цикл успешно удален.",
    "Something went wrong please try again later.": "Что-то пошло не так. Попробуйте позже.",
    "Success!": "Успех!",
    "Error!": "Ошибка!",
    "Warning!": "Предупреждение!",
    "Theme updated successfully!": "Тема успешно обновлена!",
    "Failed to update the theme": "Не удалось обновить тему",
    "Deleted successfully!": "Успешно удалено!",
    "Module added to favorites.": "Модуль добавлен в избранное.",
    "Couldn't add the module to favorites. Please try again.": "Не удалось добавить модуль в избранное. Попробуйте снова.",
    "Some error occurred": "Произошла ошибка",
    "Select date": "Выберите дату",
    "Please select a date": "Выберите дату",
    "Please select a time": "Выберите время",
    "Enter workspace name": "Введите название пространства",
    "Role is required.": "Роль обязательна.",
    "Permission denied": "Доступ запрещен",
    "Archive success": "Архивировано",
    "Your archives can be found in project archives.": "Архивы доступны в архивах проекта.",
    "Cycle could not be archived. Please try again.": "Не удалось архивировать цикл. Попробуйте снова.",
    "Estimate deleted": "Оценка удалена",
    "Estimate creation failed": "Не удалось создать оценку",
    "Page version restored.": "Версия страницы восстановлена.",
    "Failed to restore page version.": "Не удалось восстановить версию страницы.",
    "Untitled": "Без названия",
    "Set date": "Выберите дату",
    "Work item ID copied to clipboard": "ID рабочего элемента скопирован",
    "Attachment uploaded": "Вложение загружено",
    "The attachment has been successfully uploaded": "Вложение успешно загружено",
    "Attachment not uploaded": "Вложение не загружено",
    "The attachment could not be uploaded": "Не удалось загрузить вложение",
    "Attachment removed": "Вложение удалено",
    "Attachment not removed": "Вложение не удалено",
    "Title": "Название",
    "This is required": "Это поле обязательно",
    "URL is required": "URL обязателен",
    "Cannot move work item": "Не удалось переместить рабочий элемент",
    "Remove from cycle": "Удалить из цикла",
    "Remove from module": "Удалить из модуля",
    "Neutral color is required": "Нейтральный цвет обязателен",
    "Brand color is required": "Цвет бренда обязателен",
    "Type or paste a URL": "Введите или вставьте URL",
    "What you'd like to see this link as": "Как назвать эту ссылку",
    "Copied to clipboard": "Скопировано в буфер обмена",
    "Theme updated": "Тема обновлена",
    "Reloading to apply changes...": "Перезагрузка для применения изменений...",
    "Failed to update theme. Please try again.": "Не удалось обновить тему. Попробуйте снова.",
    "Tell AI what to do...": "Напишите, что сделать ИИ...",
    "Create Workspace": "Создать пространство",
    "Workspace Invitations": "Приглашения в пространство",
    "Sign up - Plane": "Регистрация - Plane",
    "Onboarding": "Первичная настройка",
    "Invitations": "Приглашения",
    "Set Password - Plane": "Задать пароль - Plane",
    "Forgot Password - Plane": "Восстановление пароля - Plane",
    "Reset Password - Plane": "Сброс пароля - Plane",
    "404 - Page Not Found": "404 - Страница не найдена",
    "Please select at least one invitation": "Выберите хотя бы одно приглашение",
    "Back to home": "На главную",
    "No pending invites": "Нет ожидающих приглашений",
    "No matching results": "Нет совпадающих результатов",
    "No Data yet": "Данных пока нет",
    "Load more": "Загрузить еще",
    "Select a language": "Выберите язык",
}

for path in Path("frontend-hotfix-all/assets").rglob("*.js"):
    text = path.read_text(encoding="utf-8", errors="ignore")
    original = text
    for old, new in repls.items():
        text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding="utf-8")
