# Generated by Codex for Workspace Groups MVP

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_module_start_time_target_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_groups", to="db.workspace")),
            ],
            options={
                "verbose_name": "Workspace Group",
                "verbose_name_plural": "Workspace Groups",
                "db_table": "workspace_groups",
                "ordering": ("sort_order", "name", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="workspacegroup",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("is_archived", False)), fields=("workspace", "name"), name="workspace_group_unique_name_workspace_active"),
        ),
        migrations.AddConstraint(
            model_name="workspacegroup",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("is_archived", False)), fields=("workspace", "slug"), name="workspace_group_unique_slug_workspace_active"),
        ),
    ]
