# Generated by Codex for Workspace Group Members

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0124_workspace_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceGroupMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_members", to="db.workspacegroup")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_group_members", to="db.workspace")),
                ("workspace_member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_group_members", to="db.workspacemember")),
            ],
            options={
                "verbose_name": "Workspace Group Member",
                "verbose_name_plural": "Workspace Group Members",
                "db_table": "workspace_group_members",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="workspacegroupmember",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("group", "workspace_member"), name="workspace_group_member_unique_group_member_active"),
        ),
    ]
