# Generated by Codex for Workspace Group emoji

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0125_workspace_group_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacegroup",
            name="emoji",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
