# Generated by Codex for workspace group emoji picker storage.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0126_workspace_group_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacegroup",
            name="emoji",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
