# Generated by Codex for Issue Pipeline MVP

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0127_workspace_group_emoji_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuePipelineItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("state_name_snapshot", models.CharField(max_length=255)),
                ("sort_order", models.FloatField(default=65535)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active"), ("completed", "Completed"), ("skipped", "Skipped")], default="pending", max_length=20)),
                ("hidden_from_board", models.BooleanField(default=True)),
                ("auto_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("child_issue", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pipeline_metadata", to="db.issue")),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_pipeline_items", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("parent_issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pipeline_items", to="db.issue")),
                ("pipeline_state", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pipeline_items", to="db.state")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={
                "verbose_name": "Issue Pipeline Item",
                "verbose_name_plural": "Issue Pipeline Items",
                "db_table": "issue_pipeline_items",
                "ordering": ("sort_order", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="issuepipelineitem",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("pipeline_state__isnull", False)), fields=("parent_issue", "pipeline_state"), name="issue_pipeline_unique_parent_state_when_active"),
        ),
    ]
