# Generated by Plane pipeline customization

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0131_issue_comment_pipeline_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="pipeline_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
